name: Build

on:
  push:
    branches:
      - 'release/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: set branch name
        run: |
          echo GITHUB_REF $GITHUB_REF
          BRANCH=${GITHUB_REF#refs/heads/release/*}
          echo Branch Name $BRANCH
          echo "::set-output name=BRANCH_NAME::$BRANCH"
        id: calculate-branch-name
      - uses: actions/github-script@0.6.0
        id: pr
        with:
          github-token: ${{ secrets.API_TOKEN_GITHUB }}
          result-encoding: string
          script: |
            const result = await github.repos.listPullRequestsAssociatedWithCommit({
              owner: context.payload.repository.owner.name,
              repo: context.payload.repository.name,
              commit_sha: context.payload.head_commit.id
            })
            return result.data[0].number;
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          githubToken: ${{ secrets.API_TOKEN_GITHUB }}
          prNumber: ${{ steps.pr.outputs.results }}
      - name: test
        run: |
          cat $HOME/files.json
          echo '${{ steps.file_changes.outputs.files}}'
      - name: Create list of files
        id: files_list
        uses: lucaspinheirogit/list-from-string-array-action@v1.4.3
        with:
          stringArray: ${{ steps.file_changes.outputs.files }}
      - name: Print modified files
        run: echo '${{ steps.files_list.outputs.stringList }}'
      - name: build
        run: |
          npm install
          node build.js
      - name: Push to proto-server
        uses: sepulsa/push_then_pr@master
        env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
            DEST_GITHUB_USERNAME: 'mlenkeit'
            DEST_REPO_NAME: 'proto-server'
            USER_EMAIL: 'test@example.com'
            PUSH_TO_BRANCH: 'chore/update-protobuf-from-${{ steps.calculate-branch-name.outputs.BRANCH_NAME }}'
            PR_TO_BRANCH: 'poc/central-protobuf-files-${{ steps.calculate-branch-name.outputs.BRANCH_NAME }}'
            SRC_DIR: 'dist/cwa-server/*'
            PR_MESSAGE: 'Update from leading repo ${{ steps.calculate-branch-name.outputs.BRANCH_NAME }}'
      - name: Push to proto-android
        uses: sepulsa/push_then_pr@master
        env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
            DEST_GITHUB_USERNAME: 'mlenkeit'
            DEST_REPO_NAME: 'proto-android'
            USER_EMAIL: 'test@example.com'
            PUSH_TO_BRANCH: 'chore/update-protobuf-from-${{ steps.calculate-branch-name.outputs.BRANCH_NAME }}'
            PR_TO_BRANCH: 'poc/central-protobuf-files-${{ steps.calculate-branch-name.outputs.BRANCH_NAME }}'
            SRC_DIR: 'dist/cwa-app-android/*'
            PR_MESSAGE: 'Update from leading repo ${{ steps.calculate-branch-name.outputs.BRANCH_NAME }}'