name: Build

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: build
        run: |
          npm install
          node build.js
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'build results'
          branch: build-results
          file_pattern: '--force dist'
          push_options: '--force'
          skip_dirty_check: true