name: Build

on:
  push:
    branches:
      - 'release/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Calculate Branch Name
        id: calculate-branch-name
        run: |
          echo GITHUB_REF $GITHUB_REF
          BRANCH=${GITHUB_REF#refs/heads/release/*}
          echo Branch Name $BRANCH
          echo "::set-output name=BRANCH_NAME::$BRANCH"
      - uses: actions/github-script@0.6.0
        name: Get PR for the commit
        id: get-pr-for-commit
        with:
          github-token: ${{ secrets.API_TOKEN_GITHUB }}
          result-encoding: string
          script: |
            const result = await github.repos.listPullRequestsAssociatedWithCommit({
              owner: context.payload.repository.owner.name,
              repo: context.payload.repository.name,
              commit_sha: context.payload.head_commit.id
            })
            return result.data[0].number;
      - name: Get file changes
        id: get-file-changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          githubToken: ${{ secrets.API_TOKEN_GITHUB }}
          prNumber: ${{ steps.get-pr-for-commit.outputs.results }}
      - name: Show file changes
        run: |
          cat $HOME/files.json
          echo '${{ steps.get-file-changes.outputs.files }}'
      - name: Find changed proto files
        id: find-proto-files
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: 'src\/proto\/\D+.proto'
          regex_flags: 'gim'
          search_string: ${{ steps.get-file-changes.outputs.files }}
      - name: Decide how should process continue
        id: decide-to-continue
        run: |
          echo 'first found proto file: ${{ steps.find-proto-files.outputs.first_match }}'
          PROCESS_CONTINUE=${{ contains(steps.find-proto-files.outputs.first_match, 'src/proto') }}
          echo PROCESS_CONTINUE $PROCESS_CONTINUE
          echo "::set-output name=process-continue::$PROCESS_CONTINUE)"
      - name: build
        if: ${{ steps.decide-to-continue.outputs.process-continue == 'true' }}
        run: |
          echo Continue? ${{ steps.decide-to-continue.outputs.process-continue }}
          echo Continue Result of Expression? ${{ steps.decide-to-continue.outputs.process-continue == 'true' }}
          npm install
          node build.js
      - name: Push to proto-server
        uses: sepulsa/push_then_pr@master
        if: ${{ steps.decide-to-continue.outputs.process-continue == 'true' }}
        env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
            DEST_GITHUB_USERNAME: 'mlenkeit'
            DEST_REPO_NAME: 'proto-server'
            USER_EMAIL: 'test@example.com'
            PUSH_TO_BRANCH: 'chore/update-protobuf-from-${{ steps.calculate-branch-name.outputs.BRANCH_NAME }}'
            PR_TO_BRANCH: 'poc/central-protobuf-files-${{ steps.calculate-branch-name.outputs.BRANCH_NAME }}'
            SRC_DIR: 'dist/cwa-server/*'
            PR_MESSAGE: 'Update from leading repo ${{ steps.calculate-branch-name.outputs.BRANCH_NAME }}'
      - name: Push to proto-android
        uses: sepulsa/push_then_pr@master
        if: ${{ steps.decide-to-continue.outputs.process-continue == 'true' }}
        env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
            DEST_GITHUB_USERNAME: 'mlenkeit'
            DEST_REPO_NAME: 'proto-android'
            USER_EMAIL: 'test@example.com'
            PUSH_TO_BRANCH: 'chore/update-protobuf-from-${{ steps.calculate-branch-name.outputs.BRANCH_NAME }}'
            PR_TO_BRANCH: 'poc/central-protobuf-files-${{ steps.calculate-branch-name.outputs.BRANCH_NAME }}'
            SRC_DIR: 'dist/cwa-app-android/*'
            PR_MESSAGE: 'Update from leading repo ${{ steps.calculate-branch-name.outputs.BRANCH_NAME }}'