name: Build

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: build
        run: |
          npm install
          node build.js
      - name: Push then create PR
        uses: sepulsa/push_then_pr@master
        env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

            DEST_GITHUB_USERNAME: 'mlenkeit'
            DEST_REPO_NAME: 'proto-server'
            USER_EMAIL: 'test@example.com'
            PUSH_TO_BRANCH: 'update-from-main'
            PR_TO_BRANCH: 'main'
            # You can add multiple source file or folder separate by space
            SRC_DIR: 'dist/cwa-server/common' 
            # You can create nested folder
            # You can rename with format source(comma)target
            # Multiple line if you want to move multiple file / folder
            # RENAME: >-
            #   cwa-server,proto
            # Add your custom Pull Request message
            PR_MESSAGE: 'Update from leading repo'
      # - name: commit
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: 'build results'
      #     branch: build-results
      #     file_pattern: '--force dist'
      #     push_options: '--force'
      #     skip_dirty_check: true