name: Build

on:
  push:
    branches:
      - 'release/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: build
        run: |
          echo Branch $GITHUB_REF
          npm install
          node build.js
      - name: Push to proto-server
        uses: sepulsa/push_then_pr@master
        env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
            DEST_GITHUB_USERNAME: 'mlenkeit'
            DEST_REPO_NAME: 'proto-server'
            USER_EMAIL: 'test@example.com'
            PUSH_TO_BRANCH: 'update-from-main'
            PR_TO_BRANCH: 'main'
            SRC_DIR: 'dist/cwa-server/*'
            PR_MESSAGE: 'Update from leading repo'
      - name: Push to proto-android
        uses: sepulsa/push_then_pr@master
        env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
            DEST_GITHUB_USERNAME: 'mlenkeit'
            DEST_REPO_NAME: 'proto-android'
            USER_EMAIL: 'test@example.com'
            PUSH_TO_BRANCH: 'update-from-main'
            PR_TO_BRANCH: 'main'
            SRC_DIR: 'dist/cwa-app-android/*'
            PR_MESSAGE: 'Update from leading repo'